// Selects the final EXACTLY 15,000 allowedWords (ranked, best-first) and a
// stricter ~3,000-5,000 answerWords subset, then renders src/data/words.js.
//
// Per the project brief: never pad with junk to hit 15,000. If fewer than
// 15,000 clean-scored candidates exist, this script throws instead of lying.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'
import { DIRS } from './lib/config.mjs'
import { toGraphemes } from './lib/config.mjs'

const TARGET_ALLOWED_COUNT = 15000
const TARGET_ANSWER_MIN = 3000
const TARGET_ANSWER_MAX = 5000
const ANSWER_MIN_SCORE = 6 // stricter bar: must look solidly like a standard, attested Bosnian word

function loadJSON(path) {
  return JSON.parse(readFileSync(path, 'utf8'))
}

const scored = loadJSON(join(DIRS.output, 'scored_words.json'))

if (scored.length < TARGET_ALLOWED_COUNT) {
  console.error(`FATAL: only ${scored.length} clean scored candidates available, need ${TARGET_ALLOWED_COUNT}.`)
  console.error('Refusing to pad the list with low-quality words. Widen sources or relax filters and re-run the pipeline.')
  process.exit(1)
}

// Already sorted best-first by score_words.mjs (score desc, then alpha).
const allowedWords = scored.slice(0, TARGET_ALLOWED_COUNT).map(s => s.word).sort()

const answerCandidates = scored.filter(s => s.score >= ANSWER_MIN_SCORE && s.isBosnianCore)
let answerWords
if (answerCandidates.length >= TARGET_ANSWER_MIN) {
  answerWords = answerCandidates.slice(0, TARGET_ANSWER_MAX).map(s => s.word).sort()
} else {
  // Fall back to the top N scored Bosnian-core words if the strict bar is too
  // aggressive to reach the minimum size.
  answerWords = scored.filter(s => s.isBosnianCore).slice(0, TARGET_ANSWER_MIN).map(s => s.word).sort()
}

// Safety: answerWords must always be a subset of allowedWords.
const allowedSet = new Set(allowedWords)
const orphanAnswers = answerWords.filter(w => !allowedSet.has(w))
if (orphanAnswers.length > 0) {
  console.warn(`${orphanAnswers.length} answerWords were not in the top ${TARGET_ALLOWED_COUNT} allowedWords; adding them in.`)
  allowedWords.push(...orphanAnswers)
  allowedWords.sort()
}

function toUpperDisplay(word) {
  // Keep storage lowercase (per brief) but the game module also exposes an
  // uppercase view for legacy compatibility with the existing engine helpers.
  return word.toUpperCase()
}

function renderModule() {
  const allowedLiteral = JSON.stringify(allowedWords, null, 2)
  const answerLiteral = JSON.stringify(answerWords, null, 2)
  return `// Auto-generated by scripts/generate_words.mjs — do not edit by hand.
// Regenerate with: npm run words:build
//
// allowedWords: every word a player may type as a guess (exactly ${TARGET_ALLOWED_COUNT}).
// answerWords: the stricter subset eligible to be chosen as the daily/free answer.
// Words are lowercase Bosnian Latin (č, ć, đ, š, ž). The digraphs dž, lj, nj are
// written as two Unicode characters but count as ONE Bosnian letter — use
// toGraphemes() from src/logic/graphemes.js to tokenize a word into 5 tiles.

export const allowedWords = ${allowedLiteral}

export const answerWords = ${answerLiteral}

export function getDailyWord(date = new Date()) {
  const dateKey = typeof date === 'string' ? date.slice(0, 10) : date.toISOString().slice(0, 10)
  let hash = 0
  for (const character of dateKey) hash = (hash * 31 + character.charCodeAt(0)) >>> 0
  return answerWords[hash % answerWords.length]
}

export function getRandomWord() {
  return answerWords[Math.floor(Math.random() * answerWords.length)]
}
`
}

mkdirSync('src/data', { recursive: true })
writeFileSync('src/data/words.js', renderModule(), 'utf8')

mkdirSync(DIRS.finalOutput, { recursive: true })
writeFileSync(join(DIRS.finalOutput, 'allowedWords.js'), `export const allowedWords = ${JSON.stringify(allowedWords, null, 2)}\n`, 'utf8')
writeFileSync(join(DIRS.finalOutput, 'answerWords.js'), `export const answerWords = ${JSON.stringify(answerWords, null, 2)}\n`, 'utf8')

// Digraph stats for the report / bonus requirement visibility.
const digraphCounts = { 'dž': 0, lj: 0, nj: 0 }
for (const word of allowedWords) {
  const graphemes = toGraphemes(word)
  for (const d of Object.keys(digraphCounts)) {
    if (graphemes.includes(d)) digraphCounts[d] += 1
  }
}

console.log('--- Generation summary ---')
console.log(`allowedWords: ${allowedWords.length}`)
console.log(`answerWords:  ${answerWords.length}`)
console.log('Digraph coverage in allowedWords (words containing at least one):')
for (const [d, count] of Object.entries(digraphCounts)) console.log(`  ${d}: ${count} words`)
console.log('Wrote src/data/words.js, output/allowedWords.js, output/answerWords.js')
